### ISSUE TITLE
404 Link Broken

### ISSUE THREAD

**Issue by tiekneeshrimp** [pnnl-predictive-phenomics/csc031-gem#1]
"Current and past memote reports can be found at https://pnnl-predictive-phenomics.github.io/csc031-gem"
#Link broken/not found, 404 error

**Comment by mcnaughtonadm** [comment]
@djinnome I think you need to add access to github pages in each of these cscXXX repos. This 404 link is because github pages is not deployed. I don't have the permissions to do this.

**Comment by djinnome** [comment]
I added "Maintain" access to the concerto team for all the cscXXX repos. Does that grant you sufficient access?

**Comment by mcnaughtonadm** [comment]
Yes! I will look into it

**Comment by mcnaughtonadm** [comment]
GH Pages is generating (so the initial link now works) but the content files are currently not being generated. Will help @VicTorres23 fix them.
