### ISSUE TITLE
No Such File Error: csc031C-less_media.csv

### ISSUE THREAD

**Issue by tiekneeshrimp** [pnnl-predictive-phenomics/csc031-gem#17]
[Errno 2] No such file or directory: 'csc031/data\\media/csc031C-less_media.csv'

^ Error when trying to run **memote run --filename "model.xml" --pytest-args "-v"**

**Comment by djinnome** [comment]
This looks like a windows-specific error.  Windows uses `\` as a path separator and unix uses `/`.  Somehow when joining `csc031/data` with `media/csc031C-less_media.csv`, the  windows `\` separator was used.

**Comment by tiekneeshrimp** [comment]
whoops was on different branch, resolved
